[project]
name = "brikz"
description = "A BrickLink API async+sync python wrapper"
dynamic = ["version"]
readme = "README.md"
license = "MIT"
authors = [
    { name = "Yassen Damyanov", email = "yd@itlabs.bg" }
]
requires-python = ">=3.12"
dependencies = []
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]

[project.urls]
Homepage = "https://github.com/ya55en/brikz"
Repository = "https://github.com/ya55en/brikz"
Issues = "https://github.com/ya55en/brikz/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "src/brikz/__init__.py"
