"""Behaviour specs for the `catalog_item` module.

Stubs only: each spec names one behaviour and has no body yet. Deleting the
module-level skip below turns this list into the TDD worklist.

Requests are values, so these need no client, no transport and no async: a
builder spec compares a returned `Request` against the path, params and
parser it should carry, and a parser spec feeds it a documented payload and
checks the model that comes back. `send` is specced in test_core.py, where
it lives.
"""

from __future__ import annotations

import pytest

pytestmark = pytest.mark.skip(reason="design stubs -- no implementation yet")


class describe_item_path:
    def it_builds_the_items_path_from_the_type_and_the_number(self): ...

    def it_appends_the_sub_resource_segments_it_is_given(self): ...

    def it_accepts_an_integer_segment(self): ...

    def it_percent_encodes_a_number_that_contains_a_slash(self): ...

    def it_percent_encodes_a_number_that_contains_a_hash(self): ...

    def it_refuses_a_blank_item_number(self): ...

    def it_refuses_a_blank_item_type(self): ...


class describe_get_item:
    def it_points_at_the_item_path(self): ...

    def it_asks_for_no_query_parameters(self): ...

    def it_reads_the_answer_as_an_item(self): ...


class describe_get_item_image:
    def it_points_at_the_image_path_for_the_color(self): ...

    def it_reads_the_answer_as_an_item(self): ...


class describe_get_supersets:
    def it_points_at_the_supersets_path(self): ...

    def it_narrows_the_supersets_to_a_single_color(self): ...

    def it_asks_for_every_color_when_given_no_color(self): ...

    def it_reads_the_answer_as_superset_entries(self): ...


class describe_get_subsets:
    def it_points_at_the_subsets_path(self): ...

    def it_narrows_the_subsets_to_a_single_color(self): ...

    def it_asks_for_the_box_and_the_instruction_when_told_to(self): ...

    def it_breaks_minifigs_and_sets_down_when_told_to(self): ...

    def it_leaves_out_every_option_it_is_not_given(self): ...

    def it_reads_the_answer_as_subset_entries(self): ...


class describe_get_price_guide:
    def it_points_at_the_price_path(self): ...

    def it_asks_for_the_sold_statistics_instead_of_the_stock_ones(self): ...

    def it_asks_for_the_used_condition(self): ...

    def it_narrows_the_price_guide_to_one_country(self): ...

    def it_narrows_the_price_guide_to_one_region(self): ...

    def it_asks_for_the_prices_in_a_given_currency(self): ...

    def it_asks_for_the_prices_with_vat_included(self): ...

    def it_leaves_out_every_option_it_is_not_given(self): ...

    def it_reads_the_answer_as_a_price_guide(self): ...


class describe_get_known_colors:
    def it_points_at_the_colors_path(self): ...

    def it_reads_the_answer_as_known_colors(self): ...


class describe_parse_item:
    def it_reads_the_documented_fields(self): ...

    def it_leaves_the_fields_bricklink_omits_unset(self): ...

    def it_reads_the_weight_and_the_dimensions_as_decimals(self): ...

    def it_reads_the_type_as_an_item_type(self): ...

    def it_survives_an_item_type_it_has_never_heard_of(self): ...


class describe_parse_superset_entries:
    def it_groups_the_including_items_by_color(self): ...

    def it_reads_the_nested_item_reference(self): ...

    def it_reads_how_each_entry_appears(self): ...


class describe_parse_subset_entries:
    def it_groups_the_included_items_by_matching(self): ...

    def it_reads_the_nested_item_reference(self): ...

    def it_marks_the_alternate_and_the_counterpart_entries(self): ...


class describe_parse_price_guide:
    def it_reads_the_price_statistics(self): ...

    def it_reads_every_price_as_a_decimal(self): ...

    def it_reads_the_stock_shaped_price_detail_rows(self): ...

    def it_reads_the_sold_shaped_price_detail_rows(self): ...

    def it_reads_the_order_date_as_a_datetime(self): ...

    def it_ignores_the_misspelled_qunatity_field(self): ...


class describe_parse_known_colors:
    def it_reads_the_color_ids_and_the_quantities(self): ...
